server:
  port: 8080  # el puerto donde escuchará el Gateway

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: job-services
          uri: lb://job-services
          predicates:
            - Path=/api/jobs/**

        - id: player-services
          uri: lb://player-services
          predicates:
            - Path=/api/players/**






eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
