server:
  port: 8080  # el puerto donde escuchará el Gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/api/jobs/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
