server:
  port: 8084   # por ejemplo, ya que 8080, 8082 y 8083 los tenemos ocupados

spring:
  application:
    name: auth-services
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


app:
  security:
    jwt:
      secret: pIGTKr9WkI1YlaYNGOB1tBJWT9s0PWu0kCf2AvUetTEmoSaQfMBYdm7PL2X5uRV0
      expiration-ms: 3600000   # 1h en milisegundos (opcional)